version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - GRADLE_OPTS=-Dorg.gradle.daemon=false
    ports:
      - "8080:8080"
      - "8085:8085"  # Firebase emulator UI port
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - FIREBASE_PROJECT_ID={FIREBASE_PROJECT_ID}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${EMAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    volumes:
      - ~/.m2:/root/.m2
      - ~/.gradle:/root/.gradle
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "8080:8080"
    environment:
      - PORT=8080 
    depends_on:
      
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge