version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8085:8085"  # Firebase emulator UI port
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-qr-code-management}
      - FIREBASE_EMULATOR_HOST=localhost:8085
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - JWT_EXPIRATION=86400000
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${EMAIL_USERNAME:-your-email}
      - SPRING_MAIL_PASSWORD=${EMAIL_PASSWORD:-your-password}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_FIREBASE_API_KEY=${FIREBASE_API_KEY:-your-firebase-api-key}
      - REACT_APP_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN:-your-auth-domain}
      - REACT_APP_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-qr-code-management}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge