on:
  push:
    branches:
       - master

    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/build-push.yml"
  workflow_dispatch:
env:
  IMAGE_NAME: qwervego-ui
  WORKING_DIRECTORY: ./frontend/
  IMAGE_TAG: dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest  # The runner environment (Ubuntu)

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud credentials (OIDC)
      id: gcloud-auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'kubectl'

    - name: Build Docker images for frontend and backend
      run: |
        docker-compose build

#    - name: Push Docker images to Google Container Registry
#      run: |
#       docker tag frontend gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest
#        docker tag backend gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest
#        docker push gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest
#        docker push gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest

#    - name: Deploy to Cloud Run (Frontend)
#      run: |
#        gcloud run deploy frontend \
#          --image gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest \
#          --platform managed \
#          --region us-central1 \
#          --allow-unauthenticated

#    - name: Deploy to Cloud Run (Backend)
#      run: |
#        gcloud run deploy backend \
#          --image gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest \
#          --platform managed \
#          --region us-central1 \
#          --allow-unauthenticated