on:

  push:
    branches:
      - master  # Trigger the workflow when a commit is pushed to the 'main' branch

  workflow_dispatch:  # Allows manual triggering of the workflow from the GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest  # The runner environment (Ubuntu)

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Set up Google Cloud credentials (OIDC)
      id: gcloud-auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        create_credentials_file: true
        export_environment_variables: true
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.3
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'kubectl'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build Docker images for frontend and backend
      run: |
        docker-compose build

    - name: Push Docker images to Google Artifact Registry
      run: |
        docker tag study-gcp-frontend asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qwervego/frontend:latest
        docker tag study-gcp-backend asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qwervego/backend:latest
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qwervego/frontend:latest
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qwervego/backend:latest

    - name: Deploy to Cloud Run (Frontend)
      run: |
        gcloud run deploy frontend \
          --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qwervego/frontend:latest \
          --platform managed \
          --port 8080 \
          --region asia-south1 \
          --set-env-vars=VITE_API_URL="https://backend-230228655056.asia-south1.run.app" \
          --allow-unauthenticated

    - name: Deploy to Cloud Run (Backend)
      run: |
        gcloud run deploy backend \
          --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qwervego/backend:latest \
          --platform managed \
          --port 8080 \
          --region asia-south1 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 1 \
          --max-instances 10 \
          --set-env-vars=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }},FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }} \
          --timeout 300 \
          --allow-unauthenticated