on:
  pull_request:
    branches:
      - master  # or 'main' depending on your default branch name
    types: [opened, synchronize, reopened]

    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/build-push.yml"
  workflow_dispatch:



permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest  # The runner environment (Ubuntu)

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

    - name: Set up Google Cloud credentials (OIDC)
      id: gcloud-auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.3
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'kubectl'

    - name: Build Docker images for frontend and backend
      run: |
        docker-compose build

    - name: Push Docker images to Google Container Registry
      run: |
       docker tag study-gcpfrontend asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/qwervego/frontend:latest
        docker tag study-gcp-backend asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/qwervego/backend:latest
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/qwervego/frontend:latest
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/qwervego/backend:latest

#    - name: Deploy to Cloud Run (Frontend)
#      run: |
#        gcloud run deploy frontend \
#          --image gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest \
#          --platform managed \
#          --region us-central1 \
#          --allow-unauthenticated

#    - name: Deploy to Cloud Run (Backend)
#      run: |
#        gcloud run deploy backend \
#          --image gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest \
#          --platform managed \
#          --region us-central1 \
#          --allow-unauthenticated